# Generated by Django 5.2.1 on 2026-01-20 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('chairperson', 'Chairperson'), ('vice_chairperson', 'Vice Chairperson'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('member', 'Board Member'), ('advisor', 'Advisor'), ('ex_officio', 'Ex-Officio Member')], default='member', max_length=50)),
                ('custom_position', models.CharField(blank=True, help_text="If 'Other' is selected", max_length=100)),
                ('bio', models.TextField(help_text='Professional biography')),
                ('short_bio', models.TextField(blank=True, help_text='Brief introduction (for cards)', max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trustees/photos/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('current_role', models.CharField(blank=True, max_length=200, verbose_name='Current Position')),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('qualifications', models.TextField(blank=True, help_text='Degrees and certifications')),
                ('linkedin', models.URLField(blank=True)),
                ('google_scholar', models.URLField(blank=True)),
                ('researchgate', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('term_start', models.DateField(default=django.utils.timezone.now)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=True, verbose_name='Currently Serving')),
                ('show_on_website', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trustee',
                'verbose_name_plural': 'Trustees',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BoardTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 2023-2025 Board', max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(blank=True, related_name='board_terms', to='trustees.trustee')),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
    ]
