# Generated by Django 5.2.1 on 2026-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardterm',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardterm',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardterm',
            name='name_ar',
            field=models.CharField(help_text='e.g., 2023-2025 Board', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boardterm',
            name='name_en',
            field=models.CharField(help_text='e.g., 2023-2025 Board', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trustee',
            name='bio_ar',
            field=models.TextField(help_text='Professional biography', null=True),
        ),
        migrations.AddField(
            model_name='trustee',
            name='bio_en',
            field=models.TextField(help_text='Professional biography', null=True),
        ),
        migrations.AddField(
            model_name='trustee',
            name='current_role_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Current Position'),
        ),
        migrations.AddField(
            model_name='trustee',
            name='current_role_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Current Position'),
        ),
        migrations.AddField(
            model_name='trustee',
            name='custom_position_ar',
            field=models.CharField(blank=True, help_text="If 'Other' is selected", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trustee',
            name='custom_position_en',
            field=models.CharField(blank=True, help_text="If 'Other' is selected", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trustee',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trustee',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trustee',
            name='organization_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trustee',
            name='organization_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trustee',
            name='qualifications_ar',
            field=models.TextField(blank=True, help_text='Degrees and certifications', null=True),
        ),
        migrations.AddField(
            model_name='trustee',
            name='qualifications_en',
            field=models.TextField(blank=True, help_text='Degrees and certifications', null=True),
        ),
        migrations.AddField(
            model_name='trustee',
            name='short_bio_ar',
            field=models.TextField(blank=True, help_text='Brief introduction (for cards)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trustee',
            name='short_bio_en',
            field=models.TextField(blank=True, help_text='Brief introduction (for cards)', max_length=300, null=True),
        ),
    ]
