# Generated by Django 5.2.1 on 2026-01-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trustees', '0002_boardterm_description_ar_boardterm_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardterm',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='boardterm',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='boardterm',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='boardterm',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='bio_ar',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='current_role_ar',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='current_role_en',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='custom_position_ar',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='custom_position_en',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='organization_ar',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='organization_en',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='qualifications_ar',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='qualifications_en',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='short_bio_ar',
        ),
        migrations.RemoveField(
            model_name='trustee',
            name='short_bio_en',
        ),
    ]
