# Generated by Django 5.2.1 on 2026-01-20 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly name', unique=True)),
                ('short_title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True, max_length=300)),
                ('conference_type', models.CharField(choices=[('international', 'International Conference'), ('national', 'National Conference'), ('workshop', 'Workshop'), ('symposium', 'Symposium'), ('webinar', 'Webinar')], default='international', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('abstract_deadline', models.DateField(blank=True, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('early_bird_deadline', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('is_online', models.BooleanField(default=False)),
                ('online_link', models.URLField(blank=True, verbose_name='Online Conference Link')),
                ('website', models.URLField(blank=True)),
                ('registration_link', models.URLField(blank=True)),
                ('submission_link', models.URLField(blank=True, verbose_name='Paper Submission Link')),
                ('organizers', models.TextField(blank=True, help_text='List of organizing committees')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('theme', models.CharField(blank=True, max_length=300)),
                ('topics', models.TextField(blank=True, help_text='Conference topics (one per line)')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='conferences/banners/')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='conferences/brochures/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('affiliation', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='conferences/speakers/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='conferences.conference')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
