# Generated by Django 5.2.1 on 2026-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='city_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='city_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='country_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='country_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='organizers_ar',
            field=models.TextField(blank=True, help_text='List of organizing committees', null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='organizers_en',
            field=models.TextField(blank=True, help_text='List of organizing committees', null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='short_description_ar',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='short_title_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='short_title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='theme_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='theme_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='topics_ar',
            field=models.TextField(blank=True, help_text='Conference topics (one per line)', null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='topics_en',
            field=models.TextField(blank=True, help_text='Conference topics (one per line)', null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='venue_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='venue_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conferencespeaker',
            name='affiliation_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conferencespeaker',
            name='affiliation_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conferencespeaker',
            name='bio_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conferencespeaker',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conferencespeaker',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conferencespeaker',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conferencespeaker',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='conferencespeaker',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
