# Generated by Django 5.2.1 on 2026-02-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_remove_conference_city_ar_remove_conference_city_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='conferences/'),
        ),
    ]
