# Generated by Django 5.2.1 on 2026-02-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_conference_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='image',
        ),
    ]
