# Generated by Django 5.2.1 on 2026-01-20 15:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('activity_type', models.CharField(choices=[('research', 'Research Project'), ('collaboration', 'Research Collaboration'), ('public_outreach', 'Public Outreach'), ('community_service', 'Community Service'), ('student_program', 'Student Program'), ('award', 'Award/Grant'), ('partnership', 'Partnership'), ('event', 'Special Event'), ('publication', 'Special Publication'), ('other', 'Other Activity')], max_length=20)),
                ('short_description', models.TextField(max_length=300)),
                ('detailed_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('principal_investigator', models.CharField(blank=True, max_length=200)),
                ('collaborators', models.TextField(blank=True, help_text='Names and institutions')),
                ('participants_count', models.IntegerField(blank=True, null=True)),
                ('funding_source', models.TextField(blank=True)),
                ('grant_number', models.CharField(blank=True, max_length=100)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_virtual', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='activities/covers/')),
                ('gallery_folder', models.CharField(blank=True, help_text='Folder name for activity photos', max_length=100)),
                ('objectives', models.TextField(blank=True, help_text='Activity objectives')),
                ('expected_outcomes', models.TextField(blank=True)),
                ('achieved_outcomes', models.TextField(blank=True, help_text='Results and impact')),
                ('publications', models.TextField(blank=True, help_text='Resulting publications')),
                ('website', models.URLField(blank=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='activities/reports/')),
                ('status', models.CharField(choices=[('planning', 'In Planning'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('upcoming', 'Upcoming')], default='ongoing', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('show_on_website', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scientific Activity',
                'verbose_name_plural': 'Scientific Activities',
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ActivityUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='activities/updates/')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='activities.scientificactivity')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('photographer', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='activities.scientificactivity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
