# Generated by Django 5.2.1 on 2026-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityphoto',
            name='caption_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activityphoto',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activityphoto',
            name='photographer_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activityphoto',
            name='photographer_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activityupdate',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activityupdate',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activityupdate',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='activityupdate',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='achieved_outcomes_ar',
            field=models.TextField(blank=True, help_text='Results and impact', null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='achieved_outcomes_en',
            field=models.TextField(blank=True, help_text='Results and impact', null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='collaborators_ar',
            field=models.TextField(blank=True, help_text='Names and institutions', null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='collaborators_en',
            field=models.TextField(blank=True, help_text='Names and institutions', null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='detailed_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='detailed_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='expected_outcomes_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='expected_outcomes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='location_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='objectives_ar',
            field=models.TextField(blank=True, help_text='Activity objectives', null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='objectives_en',
            field=models.TextField(blank=True, help_text='Activity objectives', null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='principal_investigator_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='principal_investigator_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='publications_ar',
            field=models.TextField(blank=True, help_text='Resulting publications', null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='publications_en',
            field=models.TextField(blank=True, help_text='Resulting publications', null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='short_description_ar',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='short_description_en',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scientificactivity',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
