# Generated by Django 5.2.1 on 2026-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_ar',
            field=models.CharField(default='AIESA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_en',
            field=models.CharField(default='AIESA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nav_item_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='nav_item_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
