# Generated by Django 5.2.1 on 2026-02-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_organization_address_ar_organization_address_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('summary', models.TextField(max_length=500, verbose_name='ملخص الخبر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='صورة الخبر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'الأخبار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address_ar',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='nav_item_ar',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='nav_item_en',
        ),
    ]
