# Generated by Django 5.2.1 on 2026-01-20 12:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="URL-friendly name (e.g., 'journal-of-science')", unique=True)),
                ('issn', models.CharField(blank=True, max_length=20, verbose_name='ISSN')),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True, max_length=300)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='journals/covers/')),
                ('frequency', models.CharField(default='Monthly', help_text='e.g., Monthly, Quarterly, Bi-annual', max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('editor_in_chief', models.CharField(blank=True, max_length=200)),
                ('impact_factor', models.CharField(blank=True, max_length=50)),
                ('indexing', models.TextField(blank=True, help_text='Where the journal is indexed (Scopus, Web of Science, etc.)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('upcoming', 'Upcoming')], default='active', max_length=10)),
                ('submission_link', models.URLField(blank=True, verbose_name='Manuscript Submission URL')),
                ('website_link', models.URLField(blank=True, verbose_name='Journal Website')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('issue_number', models.CharField(blank=True, max_length=20)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='journals/volumes/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='journals/pdfs/')),
                ('is_published', models.BooleanField(default=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='journals.journal')),
            ],
            options={
                'ordering': ['-year', '-volume_number'],
                'unique_together': {('journal', 'volume_number', 'issue_number')},
            },
        ),
    ]
