# Generated by Django 5.2.1 on 2026-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('journal', 'volume_number', 'issue_number')},
        ),
        migrations.AddField(
            model_name='journal',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='editor_in_chief_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='editor_in_chief_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='indexing_ar',
            field=models.TextField(blank=True, help_text='Where the journal is indexed (Scopus, Web of Science, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='indexing_en',
            field=models.TextField(blank=True, help_text='Where the journal is indexed (Scopus, Web of Science, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='publisher_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='publisher_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='short_description_ar',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='issue_number_ar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='issue_number_en',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('journal', 'volume_number', 'issue_number'), ('journal', 'volume_number', 'issue_number_ar'), ('journal', 'volume_number', 'issue_number_en')},
        ),
    ]
