# Generated by Django 5.2.1 on 2026-01-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_alter_volume_unique_together_journal_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volume',
            unique_together={('journal', 'volume_number', 'issue_number')},
        ),
        migrations.RemoveField(
            model_name='journal',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='editor_in_chief_ar',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='editor_in_chief_en',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='indexing_ar',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='indexing_en',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='publisher_ar',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='publisher_en',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='short_description_ar',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='issue_number_ar',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='issue_number_en',
        ),
    ]
