# Generated by Django 5.2.1 on 2026-01-20 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('program_type', models.CharField(choices=[('workshop', 'Workshop'), ('certificate', 'Certificate Program'), ('short_course', 'Short Course'), ('webinar', 'Webinar Series'), ('seminar', 'Seminar'), ('internship', 'Internship Program'), ('fellowship', 'Research Fellowship')], default='workshop', max_length=20)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='all_levels', max_length=20)),
                ('short_description', models.TextField(max_length=300)),
                ('detailed_description', models.TextField()),
                ('learning_objectives', models.TextField(help_text='What participants will learn')),
                ('target_audience', models.TextField(help_text='Who should attend')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('schedule', models.TextField(blank=True, help_text='Detailed schedule')),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'In-Person'), ('hybrid', 'Hybrid'), ('self_paced', 'Self-Paced')], default='online', max_length=20)),
                ('venue', models.TextField(blank=True, help_text='For offline/hybrid programs')),
                ('online_link', models.URLField(blank=True, verbose_name='Online Session Link')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_currency', models.CharField(default='USD', max_length=3)),
                ('fee_description', models.TextField(blank=True, help_text="What's included in fee")),
                ('early_bird_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('early_bird_deadline', models.DateField(blank=True, null=True)),
                ('registration_link', models.URLField(blank=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('current_participants', models.IntegerField(default=0)),
                ('brochure', models.FileField(blank=True, null=True, upload_to='training/brochures/')),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='training/syllabi/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='training/covers/')),
                ('instructors', models.TextField(help_text='Names and affiliations of instructors')),
                ('provides_certificate', models.BooleanField(default=True)),
                ('certificate_name', models.CharField(blank=True, max_length=200)),
                ('accreditation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('registration_open', 'Registration Open'), ('registration_closed', 'Registration Closed')], default='upcoming', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training Program',
                'verbose_name_plural': 'Training Programs',
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='training/resources/')),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='training.trainingprogram')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
