# Generated by Django 5.2.1 on 2026-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='accreditation_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='accreditation_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='certificate_name_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='certificate_name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='detailed_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='detailed_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='fee_description_ar',
            field=models.TextField(blank=True, help_text="What's included in fee", null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='fee_description_en',
            field=models.TextField(blank=True, help_text="What's included in fee", null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='instructors_ar',
            field=models.TextField(help_text='Names and affiliations of instructors', null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='instructors_en',
            field=models.TextField(help_text='Names and affiliations of instructors', null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='learning_objectives_ar',
            field=models.TextField(help_text='What participants will learn', null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='learning_objectives_en',
            field=models.TextField(help_text='What participants will learn', null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='schedule_ar',
            field=models.TextField(blank=True, help_text='Detailed schedule', null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='schedule_en',
            field=models.TextField(blank=True, help_text='Detailed schedule', null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='short_description_ar',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='short_description_en',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='target_audience_ar',
            field=models.TextField(help_text='Who should attend', null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='target_audience_en',
            field=models.TextField(help_text='Who should attend', null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='venue_ar',
            field=models.TextField(blank=True, help_text='For offline/hybrid programs', null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='venue_en',
            field=models.TextField(blank=True, help_text='For offline/hybrid programs', null=True),
        ),
        migrations.AddField(
            model_name='trainingresource',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingresource',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingresource',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trainingresource',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
