# Generated by Django 5.2.1 on 2026-01-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingprogram_accreditation_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogram',
            name='accreditation_ar',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='accreditation_en',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='certificate_name_ar',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='certificate_name_en',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='detailed_description_ar',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='detailed_description_en',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='fee_description_ar',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='fee_description_en',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='instructors_ar',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='instructors_en',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='learning_objectives_ar',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='learning_objectives_en',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='schedule_ar',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='schedule_en',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='short_description_ar',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='target_audience_ar',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='target_audience_en',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='venue_ar',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='venue_en',
        ),
        migrations.RemoveField(
            model_name='trainingresource',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='trainingresource',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='trainingresource',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='trainingresource',
            name='title_en',
        ),
    ]
